### ISSUE TITLE
ReferenceError: document is not defined when using on server

### ISSUE THREAD

**Issue by tenorok** [rackt/react-tabs#39]
Hello! Thank you for good tabs :-)

I faced with problem when use component on server-side:
```jsx
import React from 'react';
import ReactTabs from 'react-tabs';

const Tabs = ReactTabs.Tabs,
    TabList = ReactTabs.TabList,
    Tab = ReactTabs.Tab,
    TabPanel = ReactTabs.TabPanel;

export default React.createClass({
    render: function() {
        return (
            <Tabs>
                <TabList>
                    <Tab>One</Tab>
                    <Tab>Two</Tab>
                    <Tab>Three</Tab>
                </TabList>
                <TabPanel>
                    <h2>Hello from One</h2>
                </TabPanel>
                <TabPanel>
                    <h2>Hello from Two</h2>
                </TabPanel>
                <TabPanel>
                    <h2>Hello from Three</h2>
                </TabPanel>
            </Tabs>
        );
    }
});
```

```
ReferenceError: document is not defined
    at injectCSS (/Users/tenorok/projects/multf/node_modules/react-tabs/node_modules/js-stylesheet/jss.js:21:17)
    at jss (/Users/tenorok/projects/multf/node_modules/react-tabs/node_modules/js-stylesheet/jss.js:6:5)
    at componentWillMount (/Users/tenorok/projects/multf/node_modules/react-tabs/lib/components/Tabs.js:66:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/tenorok/projects/multf/node_modules/react/lib/ReactCompositeComponent.js:228:14)
    at wrapper [as mountComponent] (/Users/tenorok/projects/multf/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/tenorok/projects/multf/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/tenorok/projects/multf/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/tenorok/projects/multf/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/tenorok/projects/multf/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/tenorok/projects/multf/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/tenorok/projects/multf/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at wrapper [as mountComponent] (/Users/tenorok/projects/multf/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/tenorok/projects/multf/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/tenorok/projects/multf/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at wrapper [as mountComponent] (/Users/tenorok/projects/multf/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/tenorok/projects/multf/node_modules/react/lib/ReactReconciler.js:38:35) [ReferenceError: document is not defined]
```

I can't understand how fix this, can you help me please?

**Comment by tenorok** [comment]
Sorry, it's my mistake.

**Comment by texttechne** [comment]
@tenorok Actually I'm facing the same problem. Why is it your mistake? How did you solve your issue? Or to put it differently: What might I be doing wrong?

**Comment by tenorok** [comment]
@texttechne I'm so sorry, but I can't remember what exactly was the reason. It seems was a misprint in component names.
In future issues I will be immediately describe what happen.

**Comment by texttechne** [comment]
@tenorok Thanks for your reply. But to be sure, you're saying that react-tabs are working with SSR for you?

Whatever I do, they're working on the client, but rendering on the server fails with the above stack trace...

**Comment by tenorok** [comment]
@texttechne yes, I used server side rendering.
Are you sure that you using `react-tabs` installed from NPM? Not from bower?

**Comment by texttechne** [comment]
@tenorok Yep, I'm sure: we're using react-tabs and installed from npm. 

The issue is solved, when styling is disabled via:
```
ReactTabs.Tabs.setUseDefaultStyles(false);
```
Are you using the same configuration?

**Comment by tenorok** [comment]
No, react-tabs did not have this method when I tried to use them.
This was the reason for which I refused to use this component.

**Comment by zaiddag** [comment]
@tenorok setUseDefaultStyles is a function
i tried setUseDefaultStyle and that didn't exist (missing the 's' at the end)
